services:
  pyspark:
    build: .
    container_name: pyspark
    volumes:
      - ./:/usr/app

  database:
    image: postgres:17.4-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  pgdata: