services:
  pyspark:
    build: 
      context: .
      args:
        - JDBC_POSTGRES_DRIVER_FOLDER=${JDBC_POSTGRES_DRIVER_FOLDER}
        - JDBC_POSTGRES_DRIVER_VERSION=${JDBC_POSTGRES_DRIVER_VERSION}
    container_name: pyspark
    volumes:
      - ./:/usr/app
    profiles:
      - app
  
  database:
    image: postgres:17.4-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/usr/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    profiles:
      - db

  test:
    build:
      context: .
      target: test
    container_name: test
    volumes:
      - ./:/usr/app
    profiles:
      - test

volumes:
  pgdata: